name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Run Test
      run: echo "Testing successful"

    - name: Build Docker Image
      run: docker build -t budget-app .

    - name: Scan Docker Image
      run: |
        docker build -t budget-app .
        docker run --rm aquasec/trivy image budget-app

    - name: Use Secrets
      run: echo "Secrets loaded successfully"